=== SamBstorm/I3WAD22-XML/Exos/Chapitre3.1/Chap2Exo/Exo-02.dtd
<!ELEMENT Annuaire (Personne*)>
<!ELEMENT Personne (Nom, Prenom, Adresse, Telephones, Courriels)>
<!ATTLIST Personne genre (M|F) #IMPLIED>
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Adresse (Rue,Numero?,Boite?,CodePostal,Ville,Pays)>
<!ELEMENT Rue (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT Boite (#PCDATA)>
<!ELEMENT CodePostal (#PCDATA)>
<!ELEMENT Ville (#PCDATA)>
<!ELEMENT Pays (#PCDATA)>
<!ELEMENT Telephones (Telephone*)>
<!ELEMENT Telephone (#PCDATA)>
<!ATTLIST Telephone type CDATA #REQUIRED>
<!ELEMENT Courriels (Courriel*)>
<!ELEMENT Courriel (#PCDATA)>
<!ATTLIST Courriel type CDATA #REQUIRED>

=== SamBstorm/I3WAD22-XML/Exos/Chapitre3.1/Chap2Exo/Exo-02.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Annuaire SYSTEM "Exo-02.dtd">
<Annuaire>
    <Personne genre="F">
        <Nom>Beurive</Nom>
        <Prenom>Aude</Prenom>
        <Adresse>
            <Rue>Avenue des cerisiers</Rue>
            <Numero>255</Numero>
            <Boite>16</Boite>
            <CodePostal>1000</CodePostal>
            <Ville>Brussel</Ville>
            <Pays>BELGIUM</Pays>
        </Adresse>
        <Telephones>
            <Telephone type="Pro">+3280033800</Telephone>
            <Telephone type="Perso">+3280033800</Telephone>
            <Telephone type="Urgence">+32100000001</Telephone>
        </Telephones>
        <Courriels>
            <Courriel type="Pro">aude.beurive@bstorm.be</Courriel>
            <Courriel type="Pro2">aude.beurive@cognitic.be</Courriel>
        </Courriels>
    </Personne>
    <Personne genre="M">
        <Nom>Legrain</Nom>
        <Prenom>Samuel</Prenom>
        <Adresse>
            <Rue>Rue des grenadiers</Rue>
            <Numero>8</Numero>
            <Boite/>
            <CodePostal>6000</CodePostal>
            <Ville>Charleroi</Ville>
            <Pays>BELGIUM</Pays>
        </Adresse>
        <Telephones>
            <Telephone type="Pro">+3280033800</Telephone>
            <Telephone type="Perso">+3280033800</Telephone>
            <Telephone type="Urgence">+32100000001</Telephone>
        </Telephones>
        <Courriels>
            <Courriel type="Pro">samuel.legrain@bstorm.be</Courriel>
            <Courriel type="Perso">noob_killer_1987@live.be</Courriel>
        </Courriels>
    </Personne>
</Annuaire>
